### ISSUE TITLE
Accessing RPCClient class

### ISSUE THREAD

**Issue by pats2sats** [runcitadel/c-lightning-client#1]
Am trying to instantiate a RPCClient, I don't need the Plugin part of the package.
The import from cjs works great:
const { Plugin } = require('c-lightning.ts/cjs/index.cjs');
but if I want to import RPCCLient it looks like that is defined in the /dist/index.js file, not cjs.
Therefore however I try to import it into my typescript project it gives me the following error:

`Must use import to load ES Module: /Users/patrickgeyer/Desktop/sudonym/api/node_modules/c-lightning.ts/dist/index.js
require() of ES modules is not supported.
require() of /Users/patrickgeyer/Desktop/sudonym/api/node_modules/c-lightning.ts/dist/index.js from /Users/patrickgeyer/Desktop/sudonym/api/dist/main.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.`

Any idea how I can import just the RPCClient?

**Comment by AaronDewes** [comment]
There are two ways to fix this.

1) Switch your project to ESM (In your tsconfig.json)

```JSON
{
    "compilerOptions": {
         "module": "ESNext",
         "moduleResolution": "node"
     }
}
```

And don't set `esModuleInterop`.

You also need to set `"type": "module"` in your package.json.

The other solution is to wait for the next release I'm planning to publish in about 30 minutes, which will export SocketRpcClient (I'm working on adding a browser-side client for the rest-rpc plugin, so there will be multiple RpcClients).

**Comment by AaronDewes** [comment]
Version `0.1.0-alpha.1` now supports `const { Plugin, SocketApiClient } = require('c-lightning.ts/cjs/index.cjs');`

However, I haven't tested this version yet, so please let me know if it works or if you run into unexpected behavior.

**Comment by AaronDewes** [comment]
@PatrickGeyer Have you been able to try one of these? Did it work?

**Comment by pats2sats** [comment]
Hi Aaron, thanks for the hard work! I'm currently exploring if c-lightning-rest does what I need and looks like it does.

**Comment by AaronDewes** [comment]
If you need a client library for c-lightning-rest, I'm working on adding that too.

**Comment by AaronDewes** [comment]
> Hi Aaron, thanks for the hard work! I'm currently exploring if c-lightning-rest does what I need and looks like it does.

Did it do what you were looking for? Please close the issue of it did
